version: '3.9'

services:
  app:
    build: server/
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/static:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
